apiVersion: apps/v1
kind: Deployment 

metadata:
  name: nginx-deployment
spec:
  selector: 
    matchLabels:
      app: nginx

  replicas: 3

  template:
    metadata:
      labels:
        app: nginx

    spec:
      contianers:
      - name: nginx
        image: tech201-mohamed/tech201-nginx:v1
        ports:
        - containerPort: 80 